# Generated by Django 2.2.4 on 2019-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, unique=True)),
                ('post_subtitle', models.CharField(max_length=100)),
                ('post_content', models.CharField(max_length=2000)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
