# Generated by Django 2.2.4 on 2019-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
